bat/bat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("form/", include("form.urls")),
    path("sponge/", include("sponge.urls"))
]

bat/form/urls.py
from . import views
from django.urls import path

app_name="form"

urlpatterns=[
    path("register/", views.index, name="register"),
    path("", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout")
]

bat/sponge/urls.py
from django.urls import path
from . import views

app_name = "spongebob"

urlpatterns=[
    path("", views.sponge, name="sponge")
]

bat/form/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Users(AbstractUser): 
    email = models.EmailField(max_length=256, unique=True)
    
    def __str__(self) :
        return self.username

bat/sponge/models.py
from django.db import models

# Create your models here.

bat/form/views.py
from ast import arg
from email import message
import email
from http.client import HTTPResponse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from form.models import Users
# Create your views here.
# class MyForm(forms.Form) : 
#     email = forms.EmailField(label="Email",max_length=256)
#     password = forms.CharField(label="",widget=forms.PasswordInput(attrs={"autocomplete":"off"}), min_length=8)
#     confirm = forms.CharField(label="",widget=forms.PasswordInput(attrs={"autocomplete":"off"}), min_length=8)


def index(request) : 
    if request.method == "POST" :
        if request.POST["pass"] != request.POST["conf"] :
            return render(request,"forms/index.html",{
                "message" : "passwords don't match"
            })
         
        auth = authenticate(request, username= request.POST['username'], password =request.POST['pass'])
        if auth is not None : 
            return render(request,"forms/login.html",{
            "message" : "username already exists"
        })
        try :
            user = Users.objects.create_user(username=request.POST['username'], email= request.POST['email'],password= request.POST['pass'])
            login(request, user)
            return HttpResponseRedirect(reverse("spongebob:sponge"))
        except:
            return render(request,"forms/index.html",{
                "message" : "user exists"
            })
         

        
    else: 
        return render(request,"forms/index.html")



def login_user(request):
    if request.method =="POST":
        username= request.POST["email"]
        password = request.POST['pass']
        auth = authenticate(request, username=username, password=password)
        if auth is not None : 
            user = Users.objects.get(username=username)
            login(request, user)
            return HttpResponseRedirect(reverse("spongebob:sponge"))
        else :
            return render(request, "forms/login.html",{
                "message" : "user doesn't exist"
            })
    else: 
        return render(request, "forms/login.html")


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("form:register"))

bat/sponge/views.py
from importlib.metadata import requires
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def sponge(request):
    if request.user.is_authenticated : 
        return render(request, "spb/spongebob.html")
    else:
        return HttpResponseRedirect(reverse("form:login"))

bat/form/templates/forms/dont.html
{%extends "forms/layout.html"%}


{% block title%}
    done
{% endblock%}


{% block body %}
    <h1>REGISTER COMPLETE</h1>

    <ol>
        <li> username : {{request.user.username}}</li>
        <li> email : {{request.user.email}}</li>
    </ol>
{% endblock %}

bat/form/templates/forms/index.html
{% extends "forms/layout.html" %}

{% block title %}
    index
{% endblock%}


{% block body %}

<main>
    <article id="article1">
        <div class="container">
            <h1>Register</h1>
            <p style="color:red">{{message}}</p>
            <form id="register" action="{% url 'form:register' %}" method="POST">
                {% csrf_token %}
                <div id = "username">
                    <label>Username</label>
                    <input type="text" autocomplete="off" name="username">
                </div>
                <div id="Email">
                    <label>Email</label>
                    <input type="Email" autocomplete="off" autofocus name="email">
                </div>
                <div id="Pass">
                    <label>Password</label>
                    <input type="Password" autocomplete="off" name="pass">
                </div>
                <div Id="confirm">
                    <label>Confirm</label>
                    <input type="Password" autocomplete="off" name="conf">
                </div>
                <input type="submit" value="submit" style="width:4rem; height:3rem; cursor: pointer;">
                <p>already have an account ? <a href="{% url 'form:login' %}">login</a></p>
            </form>    
        </div>
    </article>
</main>

<script>
    email = document.getElementById("Email")
    pass = document.getElementById("Pass")
    conf = document.getElementById("confirm")
    container = document.getElementsByClassName("container")[0]
    divs = document.querySelectorAll("#register div")
    h1 = document.querySelector(".container h1")
    butt = document.querySelector("#register input[type='submit']")
    window.onload=()=>{
        container.style.transform = "translateY(20%)" 
    }
    setTimeout(()=>{divs.forEach((div)=>{div.style.transform ="none"})
                    h1.style.transform ="none"
                    butt.style.transform="none"}, 500)
    
    
</script>
    
{% endblock %}

bat/form/templates/forms/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} shit {% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    
    <link href="{% static 'fromsstyle/styles.css' %}" rel="stylesheet">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

bat/form/templates/forms/login.html
{% extends "forms/layout.html"%}


{% block title%}
    login
{% endblock%}


{% block body %}
<main>
    <article id="article1">
        <div class="container">
            <h1>Login</h1>
            <p style="color:red">{{message}}</p>
            <form id="register" action="{% url 'form:login' %}" method="POST">
                {% csrf_token %}
                <div id="Email">
                    <label>Username</label>
                    <input type="text" autocomplete="off" autofocus name="email">
                </div>
                <div id="Pass">
                    <label>Password</label>
                    <input type="Password" autocomplete="off" name="pass">
                </div>
                <div id="submit"> 
                    <p>don't have an acount ?<a href="{% url 'form:register'%}">register</a></p>
                    <input type="submit" value="login" style="width:4rem; height:3rem; cursor: pointer;">
                </div>
              
            </form>    
        </div>
    </article>
</main>

<script>
    email = document.getElementById("Email")
    pass = document.getElementById("Pass")
    container = document.getElementsByClassName("container")[0]
    divs = document.querySelectorAll("#register div")
    h1 = document.querySelector(".container h1")
    butt = document.querySelector("#register input[type='submit']")
    window.onload=()=>{
        container.style.transform = "translateY(20%)" 
    }
    setTimeout(()=>{divs.forEach((div)=>{div.style.transform ="none"})
                    h1.style.transform ="none"
                    butt.style.transform="none"}, 500)
    
    
</script>

{% endblock %}

bat/sponge/templates/spb/index.html
{% extends "reg/layout.html" %}

{% block title %}
    register
{% endblock%}

{% block body %}
    <form action="{% url 'register' %}" mathod="post">
        {% csrf_token%}
        {{form}}
    </form>
{% endblock %}

bat/sponge/templates/spb/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock%}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

bat/sponge/templates/spb/spongebob.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <title>SpongeBob</title>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="font-size:1.5rem; margin-right:1.5rem;">SpongeBob</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown link
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>               
  </header>
  <div class="bg1">
    <main>
      <section>
        <div class="cont1">
            <h1>SpongeBob</h1>
              <div class="cards">
                <div class="card">
                  <div class="cards-overlay">
                      <div class="cardcont">
                        <img src="{% static 'img/345827.jpg' %}" alt="spongebob">
                        <div class="textt">
                          <p>Are you ready kid?
                          hay hay captain!    
                          </p>
                          <p>owwwwwwwwwwwwwwwwwww</p>
                        </div>  
                        <button type="button"><a>patrick</a></button>  
                      </div>
                    </div>
                </div>
                <div class="card">
                  <div class="cards-overlay">
                    <div class="cardcont">
                      <img src="{% static 'img/spn2.jpg' %}" alt="spongeeeebob">
                      <div class="textt">
                        <p>Who lives in a sea and people adore?</p>
                        <p>Whats the shape of spongebobs shit? is it also square shaped and how does he even poop ? he has alot of holes in his body.</p>
                      </div>  
                      <button type="button"><a>patrick</a></button>  
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="cards-overlay">
                    <div class="cardcont">
                      <img src="{% static 'img/spn3.jpg' %}" alt="spongebob">
                      <div class="textt">
                        <p>Are you ready kid?
                        hay hay captain!    
                        </p>
                        <p>owwwwwwwwwwwwwwwwwww</p>
                      </div>  
                      <button type="button"><a>patrick</a></button>  
                    </div>
                  </div>
                </div>
              </div>
              <img id="sponge" alt="spongebob" src="{% static 'img/Sbob.png' %}">
            </div>
          </section>
      </main>
    </div>
    <section>
      <div class="bg2" style='background-image:url("{%static '/img/wp.jpg' %}")'>
        <!-- <div class="scroll-bar">
          <div class="scrollcont">
            <div class="scrollimgs">
              <img class="sbimgs" id="img1" src="img/img1.jpg" alt="spongebob">
              <img class="sbimgs" id="img2" src="img/img2.jpg" alt="">
              <img class="sbimgs" id="img3" src="img/img3.jpg" alt="">
              <img class="sbimgs" id="img4" src="img/img4.jpg" alt="">
              <img class="sbimgs" id="img5" src="img/img5.jpg" alt="">
            </div>    
          </div>
        </div> -->
        <div style="transform:scale(0.5) translateY(-40%);" id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
              <div class="carousel-item active">
                  <img class="d-block w-100" src="{% static 'img/img3.jpg' %}" alt="First slide">
                  <div class="carousel-caption d-none d-md-block">
                      <h5></h5>
                      <p></p>
                  </div>
              </div>
              <div class="carousel-item">
                  <img class="d-block w-100" src="{% static 'img/img1.jpg' %}" alt="Second slide">
              </div>
              <div class="carousel-item">
                  <img class="d-block w-100" src="{% static 'img/img2.jpg' %}" alt="Third slide">
              </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
          </a>
      </div>
      </div>
        
    </section>

    <section>
      <div class="bg3" style="background-image:url({%static '/img/img3.jpg' %})" >
        <div class="inf">
          {% if user.is_authenticated %}
            <p>{{ user.email}}</p>
            <a href="{% url 'form:logout' %}" style="cursor:pointer">logout</a>
          {% endif %}
        </div>
      </div>
    </section>
  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="./script.js"></script>   
</body>
</html>